# Generated by Django 4.2.11 on 2026-01-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='atualizao',
            new_name='atualizacao',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='atualizao',
            new_name='atualizacao',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
